#ifndef SDL_DEFINES_H
#define	SDL_DEFINES_H

enum button_sprite_t
{
	BUTTON_SPRITE_MOUSE_OUT = 0,
	BUTTON_SPRITE_MOUSE_OVER_MOTION = 1,
	BUTTON_SPRITE_MOUSE_DOWN = 2,
	BUTTON_SPRITE_MOUSE_UP = 3,
	BUTTON_SPRITE_TOTAL = 4
};

#endif	/* SDL_DEFINES_H */
